### ISSUE TITLE
Run glitch with 0 and 9 (master branch, main has no sources)

### ISSUE THREAD

**Issue by ohenley** [ButcherAdaCore/AdasMasterMind#1]
Here is a glitchy run output (or I do not understand the game)
```
Enter guess number  1
1
2345
****
Enter guess number  2
0987
%@**
Enter guess number  3
6905
*%*%
Enter guess number  4
0987
%@**
Enter guess number  5
0000
*@**
Enter guess number  6
0900
*@**
```

**Comment by ButcherAdaCore** [comment]
Hmmm... good spot! That's definitely a bug.

The extra '1' char in the output at the start is curious. I'm wondering if everything is slightly offset.

**Comment by ButcherAdaCore** [comment]
Fixed - code now correctly detects an incorrect input
